_wandb:
    value:
        cli_version: 0.23.1
        code_path: code/cleanrl/cleanrl/ppo_continuous_action_v2_1.py
        e:
            c5jdp3dobvxkr6hc57kzek1f74lgljqb:
                codePath: cleanrl\cleanrl\ppo_continuous_action_v2_1.py
                codePathLocal: cleanrl\cleanrl\ppo_continuous_action_v2_1.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2000396320768"
                        used: "1032866095104"
                email: wlsrnjs7013@korea.ac.kr
                executable: C:\Users\wlsrn\anaconda3\envs\ur5\python.exe
                git:
                    commit: 2d1ca9ec662a8d59ab280b93e7fcc288409dfb24
                    remote: https://github.com/Supernova0417/UR5.git
                gpu: NVIDIA GeForce GTX 1060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1280
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1060
                      uuid: GPU-145be6bd-ea39-f6eb-e97a-4e88a30395f2
                host: LAPTOP1-SUPERNOVA
                memory:
                    total: "8256249856"
                os: Windows-10-10.0.19045-SP0
                program: D:\★박진권★\★고려대학교★\4-2 정리해야함\지능로봇공학(영강)\final\UR5\cleanrl\cleanrl\ppo_continuous_action_v2_1.py
                python: CPython 3.10.19
                root: D:\★박진권★\★고려대학교★\4-2 정리해야함\지능로봇공학(영강)\final\UR5
                startedAt: "2025-12-29T10:36:18.287155Z"
                writerId: c5jdp3dobvxkr6hc57kzek1f74lgljqb
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
                - 61
            "4": 3.10.19
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
anneal_lr:
    value: true
batch_size:
    value: 16384
capture_video:
    value: false
clip_coef:
    value: 0.2
clip_vloss:
    value: true
cuda:
    value: true
ent_coef:
    value: 0.003
env_id:
    value: UR5-ppo-v2-1
exp_name:
    value: ppo_continuous_action_v2_1
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
hf_entity:
    value: ""
learning_rate:
    value: 5e-05
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 512
norm_adv:
    value: true
num_envs:
    value: 8
num_iterations:
    value: 122
num_minibatches:
    value: 32
num_steps:
    value: 2048
save_model:
    value: true
seed:
    value: 1
target_kl:
    value: null
target_mode:
    value: random
target_pos:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 2000000
track:
    value: true
update_epochs:
    value: 10
upload_model:
    value: false
vf_coef:
    value: 0.5
wandb_entity:
    value: null
wandb_project_name:
    value: ur5
