_wandb:
    value:
        cli_version: 0.23.1
        code_path: code/cleanrl/cleanrl/sac_continuous_action_v2.py
        e:
            zjs4c2lnl45mb36vdzh68n03evnnpxf1:
                codePath: cleanrl\cleanrl\sac_continuous_action_v2.py
                codePathLocal: cleanrl\cleanrl\sac_continuous_action_v2.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "2000396320768"
                        used: "1032514904064"
                email: wlsrnjs7013@korea.ac.kr
                executable: C:\Users\wlsrn\anaconda3\envs\ur5\python.exe
                git:
                    commit: a0bc001d5313a3f9012be07380ef6a09e48fe018
                    remote: https://github.com/Supernova0417/UR5.git
                gpu: NVIDIA GeForce GTX 1060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 1280
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1060
                      uuid: GPU-145be6bd-ea39-f6eb-e97a-4e88a30395f2
                host: LAPTOP1-SUPERNOVA
                memory:
                    total: "8256249856"
                os: Windows-10-10.0.19045-SP0
                program: D:\★박진권★\★고려대학교★\4-2 정리해야함\지능로봇공학(영강)\final\UR5\cleanrl\cleanrl\sac_continuous_action_v2.py
                python: CPython 3.10.19
                root: D:\★박진권★\★고려대학교★\4-2 정리해야함\지능로봇공학(영강)\final\UR5
                startedAt: "2025-12-28T17:22:23.945020Z"
                writerId: zjs4c2lnl45mb36vdzh68n03evnnpxf1
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
                - 61
            "4": 3.10.19
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
alpha:
    value: 0.05
autotune:
    value: true
batch_size:
    value: 256
buffer_size:
    value: 1000000
capture_video:
    value: false
cuda:
    value: true
env_id:
    value: UR5-sac-v2
exp_name:
    value: sac_continuous_action_v2
gamma:
    value: 0.99
learning_starts:
    value: 5000
num_envs:
    value: 1
policy_frequency:
    value: 1
policy_lr:
    value: 0.0003
q_lr:
    value: 0.001
save_model:
    value: true
seed:
    value: 1
target_mode:
    value: random
target_network_frequency:
    value: 1
target_pos:
    value: null
tau:
    value: 0.01
torch_deterministic:
    value: true
total_timesteps:
    value: 1000000
track:
    value: true
wandb_entity:
    value: null
wandb_project_name:
    value: ur5
